/**
 * Compare SmilesDrawer's R/S stereochemistry assignments against RDKit reference.
 *
 * The reference file (reference.json) is generated by generate-reference.py using
 * RDKit's CIP assignment.
 *
 * Atom indices differ between RDKit and SmilesDrawer because SmilesDrawer creates
 * explicit vertices for bracket hydrogens (e.g. [C@@H] → C vertex + H vertex),
 * while RDKit only counts heavy atoms. So we match stereocenters by their ORDER
 * of appearance in the SMILES, not by absolute index.
 *
 * Run:  npm test -- test/stereo-reference/stereo-vs-rdkit.test.js
 */
import {describe, it, expect} from 'vitest';
import {createJSDOM}          from '../helpers';

import Parser    from '../../src/Parser.js';
import SvgDrawer from '../../src/SvgDrawer.js';

import reference from './reference.json' with {type: 'json'};

function renderAndGetStereo(smiles) {
    const dom = createJSDOM();

    const svg = dom.window.document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    svg.setAttributeNS(null, 'id', 'test-svg');
    dom.window.document.body.appendChild(svg);

    const tree = Parser.parse(smiles);
    const drawer = new SvgDrawer({isomeric: true});
    drawer.draw(tree, svg, 'light', false);

    const pp = drawer.preprocessor;
    const centers = [];

    for (let i = 0; i < pp.graph.vertices.length; i++) {
        const v = pp.graph.vertices[i];
        if (v.value.isStereoCenter) {
            centers.push({
                atomIdx: i,
                element: v.value.element,
                cip: v.value.chirality,
            });
        }
    }

    // Sort by atomIdx to preserve SMILES order
    centers.sort((a, b) => a.atomIdx - b.atomIdx);
    return centers;
}

describe('Stereochemistry: SmilesDrawer vs RDKit', () => {
    for (const [smiles, ref] of Object.entries(reference)) {
        const name = ref.name;
        // RDKit centers are already sorted by atomIdx from the Python script
        const expected = ref.centers.slice().sort((a, b) => a.atomIdx - b.atomIdx);

        it(`${name}: matches RDKit R/S assignments`, () => {
            const actual = renderAndGetStereo(smiles);

            // Check same number of stereocenters
            if (actual.length !== expected.length) {
                console.log(`  ${name}: center count mismatch`);
                console.log(`    RDKit (${expected.length}):`, expected.map(c => `${c.atomIdx}(${c.element})=${c.cip}`).join(', '));
                console.log(`    SD    (${actual.length}):`, actual.map(c => `${c.atomIdx}(${c.element})=${c.cip}`).join(', '));
            }
            expect(actual.length, `Stereocenter count: RDKit=${expected.length} vs SD=${actual.length}`).toBe(expected.length);

            // Match 1-to-1 by order of appearance (both sorted by atomIdx)
            for (let i = 0; i < expected.length; i++) {
                const exp = expected[i];
                const act = actual[i];

                // Sanity check: elements should match
                expect(act.element, `Center #${i + 1}: element mismatch (RDKit=${exp.element} at idx ${exp.atomIdx}, SD=${act.element} at idx ${act.atomIdx})`).toBe(exp.element);

                // The actual test: R/S must agree
                if (act.cip !== exp.cip) {
                    console.log(`  ${name} center #${i + 1}: R/S MISMATCH`);
                    console.log(`    RDKit: atom ${exp.atomIdx}(${exp.element}) = ${exp.cip}`);
                    console.log(`    SD:    atom ${act.atomIdx}(${act.element}) = ${act.cip}`);
                }
                expect(act.cip, `Center #${i + 1} (${act.element}): RDKit=${exp.cip} vs SD=${act.cip}`).toBe(exp.cip);
            }
        });
    }
});
