"""
Generate reference chemical formulae with RDKit.

Usage:
    python3 generate.py
"""
import json
import os
from rdkit import Chem
from rdkit.Chem.rdMolDescriptors import CalcMolFormula


MOLECULES = {
    # Single Heavy Atoms
    'Borane':            'B',
    'Methane':           'C',
    'Ammonia':           'N',
    'Water':             'O',
    'Hydrofluoric Acid': 'F',
    'Phosphene':         'P',
    'Hydrogen Sulfide':  'S',
    'Hydrochloric Acid': 'Cl',
    'Hydrogen Bromide':  'Br',
    'Hydrogen Iodide':   'I',

    # Simple Aromatic Rings
    'Benzene v1':     'c1ccccc1',
    'Benzene v2':     'C1=CC=CC=C1',
    'Pyrrole v1':     '[nH]1cccc1',
    'Pyrrole v2':     'N1C=CC=C1',
    'Pyridine v1':    'n1ccccc1',
    'Pyridine v2':    'N1=CC=CC=C1',
    'Furan v1':       'o1cccc1',
    'Furan v2':       'O1C=CC=C1',
    'Phosphole v1':   '[pH]1cccc1',
    'Phosphole v2':   'P1C=CC=C1',
    'Phosphorine v1': 'p1ccccc1',
    'Phosphorine v2': 'P1=CC=CC=C1',
    'Thiophene v1':   's1cccc1',
    'Thiophene v2':   'S1C=CC=C1',

    # Complex Drugs & Natural Products
    'Quinine':      'OC(c1ccnc2ccc(OC)cc12)[C@@H]3C[C@H]4CC[C@@H](C3)N4C=C',
    'Quinidine':    'OC(c1ccnc2ccc(OC)cc12)[C@H]3C[C@@H]4CC[C@H](C3)N4C=C',
    'Erythromycin': 'CC[C@@H]1OC(=O)[C@H](C)[C@@H](O[C@H]2C[C@@](C)(OC)[C@@H](O)[C@H](C)O2)[C@H](C)[C@@H](O[C@@H]3O[C@H](C)C[C@@H]([C@H]3O)N(C)C)[C@](C)(O)C[C@@H](C)C(=O)[C@H](C)[C@@H](O)[C@]1(C)O',
    'Doxorubicin':  'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)(C[C@@H]3O[C@H]1C[C@H](N)[C@H](O)[C@H](C)O1)C(=O)CO',
    'Vinblastine':  '[H][C@]89CN(CCc1c([nH]c2ccccc12)[C@@](C(=O)OC)(c3cc4c(cc3OC)N(C)[C@@]5([H])[C@@](O)(C(=O)OC)[C@H](OC(C)=O)[C@]7(CC)C=CCN6CC[C@]45[C@@]67[H])C8)C[C@](O)(CC)C9',
    'Strychnine':   'O=C1C[C@H]2OCC=C3C[C@H]4[C@@H](N5CC[C@@]61[C@@H]5C=CC4)N3C6=CC=C2',
    'Reserpine':    'CO[C@H]1[C@@H](CC2=C1NC1=CC(OC)=CC=C21)C(=O)OC',
    'Colchicine':   'CC(=O)N[C@H]1CCC2=CC(=C(C(=C2C3=CC=C(C(=O)C=C13)OC)OC)OC)OC',
    'Atorvastatin': 'CC(C)c1n(CC[C@@H](O)C[C@@H](O)CC(=O)O)c(c2ccc(F)cc2)c(c1c1ccccc1)C(=O)Nc1ccccc1',
    'Simvastatin':  'CCC(C)(C)C(=O)O[C@H]1C[C@@H](O)C=C2C=C[C@H](C)[C@H](CC[C@@H](O)CC(=O)O)[C@@H]21',
    'Lovastatin':   'CC[C@H](C)C(=O)O[C@H]1C[C@@H](O)C=C2C=C[C@H](C)[C@H](CC[C@@H](O)CC(=O)O)[C@@H]21',
    'Methotrexate': 'CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(C(=O)N[C@@H](CCC(=O)O)C(=O)O)cc1',
    'Captopril':    'C[C@@H](CS)C(=O)N1CCC[C@H]1C(=O)O',
    'Enalapril':    'CCOC(=O)[C@@H](CCc1ccccc1)N[C@@H](C)C(=O)N1CCC[C@H]1C(=O)O',
    'Lisinopril':   'NCCCC[C@@H](N[C@@H](CCc1ccccc1)C(=O)O)C(=O)N1CCC[C@H]1C(=O)O',
    'Warfarin':     'CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O',
    'Clopidogrel':  'COC(=O)[C@H](c1ccccc1Cl)N1CCc2sccc2C1',
    'Oseltamivir':  'CCOC(=O)C1=C[C@@H](OC(CC)CC)[C@H](NC(C)=O)[C@@H](N)C1',
    'Lopinavir':    'CC(C)[C@@H](NC(=O)[C@@H](CC(=O)N[C@H](Cc1ccccc1)[C@H](O)C[C@@H](Cc1ccccc1)NC(=O)C(C)(C)C)CC1CCCCCC1)C(=O)O',
    'Ritonavir':    'CC(C)[C@@H](NC(=O)N(C)Cc1csc(n1)C(C)C)C(=O)N[C@@H](C[C@@H](O)[C@H](Cc1ccccc1)NC(=O)OCc1cncs1)Cc1ccccc1',
}


def main():
    results = []

    for name, smiles in MOLECULES.items():
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            print(f"RDKit could not parse {name} ({smiles})")
            continue

        Chem.AddHs(mol)
        formula = CalcMolFormula(mol)

        results.append({
            'name':    name,
            'smiles':  smiles,
            'formula': formula
        })

    # Write reference file
    path = os.path.join(os.path.dirname(__file__), 'reference.json')
    with open(path, 'w') as f:
        data = {
            'WARNING': 'Autogenerated by generate.py - manual edits will be lost!',
            'tests': results
        }

        json.dump(data, f, indent=2)

    print(f"Wrote {len(results)} test cases to {path}")


if __name__ == '__main__':
    main()
